version: '3.1'
services:
  web:
    build:
      context: ./etc/docker
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - webtest
    volumes:
      - "${PWD}/code/website:/app"
  webtest:
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile.test
