version: '3.1'
services:
  web:
    build:
      context: ./etc/docker
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    env_file:
      - .env
    volumes:
      - "${PWD}/code/website:/app"
    networks:
      - minikube

networks:
  minikube:
    external: true