version: '3.1'
services:
  web:
    build:
      context: ./etc/docker
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - webtest
    volumes:
      - "${PWD}/code/src:/app"
  webtest:
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile.test
  cypress:
    build:
      context: ./etc/docker
      dockerfile: Dockerfile.cypress
    env_file:
      - .env
    user: ${USERID}:${GROUPID}
    depends_on:
      - web
    volumes:
      - "${PWD}/code/cypress:/app"