version: "3.1"
services:
  api:
    image: node:22-alpine
    ports:
      - "3000:3000"
    env_file:
      - ${PWD}/src/server/.env
    command: "node /app/index.js"
    volumes:
      - "${PWD}/src/server/dist:/app/"
      - "${PWD}/src/server/node_modules:/app/node_modules"
    networks:
      - minikube
  web:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - "${PWD}/src/client/dist:/usr/share/nginx/html"
    networks:
      - minikube

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    user: "${K3UID}:${K3GID}"
    env_file:
      - .env
    volumes:
      - "${PWD}/data/db:/var/lib/mysql"
      - "${PWD}/etc/sql:/docker-entrypoint-initdb.d"
    networks:
      - minikube

  build-web:
    image: node:lts-slim
    user: "${K3UID}:${K3GID}"
    env_file:
      - .env
    volumes:
      - "${PWD}/src/:/app/src/"
    networks:
      - minikube

networks:
  minikube:
    external: true
