FROM node:22-alpine AS builder

WORKDIR /app
COPY src/client/ ./client/
COPY src/common ./common/

RUN cd common ; yarn install ; yarn build
RUN cd client ; yarn install ; yarn build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
EXPOSE 80
