FROM node:22-alpine AS builder

ARG GIT_TAG
ENV GIT_TAG ${GIT_TAG}

WORKDIR /app
COPY src/serverside/ ./
RUN yarn install
RUN yarn build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

ARG USERID=1001
ARG GROUPID=1001
ENV USERID ${USERID}
ENV GROUPID ${GROUPID}

COPY --from=builder /app/dist .
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000

CMD ["node", "/app/index.js"]