FROM node:22-alpine AS builder

WORKDIR /app
COPY src/server/ ./server/
COPY src/common ./common/

RUN cd common ; yarn install ; yarn build
RUN cd server ; yarn install ; yarn build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

ARG GIT_TAG
ENV GIT_TAG ${GIT_TAG}

COPY --from=builder /app/server/dist .
COPY --from=builder /app/server/node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000

CMD ["node", "/app/index.js"]