apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: jsc-cluster-role-binding

roleRef:
  kind: ClusterRole
  name: jsc-cluster-role
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: jsc-service-account
    namespace: default